
const actionTypes = {
	CALENDAR_VIEW:'CALENDAR_VIEW',
	CALENDAR_ADD_EVENT:'CALENDAR_ADD_EVENT',
	CALENDAR_EDIT_EVENT:'CALENDAR_EDIT_EVENT',
	CALENDAR_DELETE_EVENT:'CALENDAR_DELETE_EVENT',
}

export default actionTypes